DOWNLOAD_LOOKBACK = "2y"  # covers all three timeframes from one download

TIMEFRAMES = {
    "5d": {
        "label": "5-Day",
        "description": "Short-term swing — enter Monday, exit Friday",
        "min_data_days": 80,
        # RSI zones
        "rsi_recover": (30, 50),
        "rsi_bullish": (50, 65),
        # Stochastic
        "stoch_oversold": 20,
        "stoch_caution": 30,
        # Moving averages
        "sma_fast": 20,
        "sma_slow": 50,
        # Bollinger
        "bb_period": 20,
        # Volume
        "vol_recent": 5,
        "vol_avg": 20,
        # OBV comparison window
        "obv_window": 10,
        # Momentum
        "mom_days": 6,
        "mom_atr_range": (0.3, 2.5),
        # Relative strength lookback (trading days)
        "rs_days": 21,
        # Golden cross scan (None = disabled)
        "golden_cross_lookback": None,
        # Score weights
        "score_rsi_recover": 25,
        "score_stoch_cross": 20,
        "score_macd_cross": 25,
        "score_macd_positive": 10,
        "score_sma_aligned": 20,
        "score_bb_below": 15,
        "score_bb_near": 10,
        "score_obv_divergence": 20,
        "score_obv_rising": 10,
        "score_vol_surge": 15,
        "score_vol_above": 7,
        "score_momentum": 10,
        "score_rs_leader": 15,
        "score_rs_outperform": 7,
        "score_golden_cross": 0,
        # Forecast
        "forecast_atr_days": 5,
        "atr_score_div": 80,
        # Exit rules
        "take_profit_pct": 5.0,
        "stop_loss_pct": 3.0,
        "hold_days": 5,
    },
    "30d": {
        "label": "30-Day",
        "description": "Medium-term position — hold ~1 calendar month",
        "min_data_days": 150,
        "rsi_recover": (40, 60),
        "rsi_bullish": (55, 70),
        "stoch_oversold": 30,
        "stoch_caution": 40,
        "sma_fast": 50,
        "sma_slow": 200,
        "bb_period": 20,
        "vol_recent": 10,
        "vol_avg": 50,
        "obv_window": 20,
        "mom_days": 21,
        "mom_atr_range": (0.5, 5.0),
        "rs_days": 63,
        "golden_cross_lookback": None,
        "score_rsi_recover": 20,
        "score_stoch_cross": 15,
        "score_macd_cross": 20,
        "score_macd_positive": 15,
        "score_sma_aligned": 25,
        "score_bb_below": 10,
        "score_bb_near": 7,
        "score_obv_divergence": 20,
        "score_obv_rising": 10,
        "score_vol_surge": 15,
        "score_vol_above": 7,
        "score_momentum": 10,
        "score_rs_leader": 20,
        "score_rs_outperform": 10,
        "score_golden_cross": 0,
        "forecast_atr_days": 30,
        "atr_score_div": 60,
        "take_profit_pct": 12.0,
        "stop_loss_pct": 6.0,
        "hold_days": 30,
    },
    "180d": {
        "label": "180-Day",
        "description": "Long-term position — hold ~6 calendar months",
        "min_data_days": 300,
        "rsi_recover": (45, 65),
        "rsi_bullish": (60, 75),
        "stoch_oversold": 40,
        "stoch_caution": 50,
        "sma_fast": 50,
        "sma_slow": 200,
        "bb_period": 50,
        "vol_recent": 20,
        "vol_avg": 100,
        "obv_window": 40,
        "mom_days": 63,
        "mom_atr_range": (1.0, 10.0),
        "rs_days": 126,
        "golden_cross_lookback": 30,
        "score_rsi_recover": 15,
        "score_stoch_cross": 10,
        "score_macd_cross": 10,
        "score_macd_positive": 20,
        "score_sma_aligned": 30,
        "score_bb_below": 10,
        "score_bb_near": 5,
        "score_obv_divergence": 15,
        "score_obv_rising": 10,
        "score_vol_surge": 10,
        "score_vol_above": 5,
        "score_momentum": 10,
        "score_rs_leader": 25,
        "score_rs_outperform": 12,
        "score_golden_cross": 20,
        "forecast_atr_days": 180,
        "atr_score_div": 40,
        "take_profit_pct": 25.0,
        "stop_loss_pct": 12.0,
        "hold_days": 180,
    },
}
