DOWNLOAD_LOOKBACK = "3y"  # covers all three timeframes including 1-year RS lookback

TIMEFRAMES = {
    "30d": {
        "label": "30-Day",
        "description": "Medium-term position — hold ~1 calendar month",
        "min_data_days": 150,
        "rsi_recover": (40, 60),
        "rsi_bullish": (55, 70),
        "stoch_oversold": 30,
        "stoch_caution": 40,
        "sma_fast": 50,
        "sma_slow": 200,
        "bb_period": 20,
        "vol_recent": 10,
        "vol_avg": 50,
        "obv_window": 20,
        "mom_days": 21,
        "mom_atr_range": (0.5, 5.0),
        "rs_days": 63,
        "golden_cross_lookback": None,
        "score_rsi_recover": 20,
        "score_stoch_cross": 15,
        "score_macd_cross": 20,
        "score_macd_positive": 15,
        "score_sma_aligned": 25,
        "score_bb_below": 10,
        "score_bb_near": 7,
        "score_obv_divergence": 20,
        "score_obv_rising": 10,
        "score_vol_surge": 15,
        "score_vol_above": 7,
        "score_momentum": 10,
        "score_rs_leader": 20,
        "score_rs_outperform": 10,
        "score_golden_cross": 0,
        "forecast_atr_days": 30,
        "atr_score_div": 60,
        "take_profit_pct": 12.0,
        "stop_loss_pct": 6.0,
        "hold_days": 30,
    },
    "180d": {
        "label": "180-Day",
        "description": "Long-term position — hold ~6 calendar months",
        "min_data_days": 300,
        "rsi_recover": (45, 65),
        "rsi_bullish": (60, 75),
        "stoch_oversold": 40,
        "stoch_caution": 50,
        "sma_fast": 50,
        "sma_slow": 200,
        "bb_period": 50,
        "vol_recent": 20,
        "vol_avg": 100,
        "obv_window": 40,
        "mom_days": 63,
        "mom_atr_range": (1.0, 10.0),
        "rs_days": 126,
        "golden_cross_lookback": 30,
        "score_rsi_recover": 15,
        "score_stoch_cross": 10,
        "score_macd_cross": 10,
        "score_macd_positive": 20,
        "score_sma_aligned": 30,
        "score_bb_below": 10,
        "score_bb_near": 5,
        "score_obv_divergence": 15,
        "score_obv_rising": 10,
        "score_vol_surge": 10,
        "score_vol_above": 5,
        "score_momentum": 10,
        "score_rs_leader": 25,
        "score_rs_outperform": 12,
        "score_golden_cross": 20,
        "forecast_atr_days": 180,
        "atr_score_div": 40,
        "take_profit_pct": 25.0,
        "stop_loss_pct": 12.0,
        "hold_days": 180,
    },
    "1y": {
        "label": "1-Year",
        "description": "Long-term trend — hold ~1 full trading year",
        "min_data_days": 400,
        "rsi_recover": (50, 70),
        "rsi_bullish": (65, 80),
        "stoch_oversold": 40,
        "stoch_caution": 55,
        "sma_fast": 50,
        "sma_slow": 200,
        "bb_period": 50,
        "vol_recent": 20,
        "vol_avg": 100,
        "obv_window": 60,
        "mom_days": 126,
        "mom_atr_range": (2.0, 15.0),
        "rs_days": 252,
        "golden_cross_lookback": 60,
        "score_rsi_recover": 10,
        "score_stoch_cross": 8,
        "score_macd_cross": 8,
        "score_macd_positive": 25,
        "score_sma_aligned": 35,
        "score_bb_below": 8,
        "score_bb_near": 5,
        "score_obv_divergence": 12,
        "score_obv_rising": 10,
        "score_vol_surge": 8,
        "score_vol_above": 5,
        "score_momentum": 8,
        "score_rs_leader": 30,
        "score_rs_outperform": 15,
        "score_golden_cross": 25,
        "forecast_atr_days": 252,
        "atr_score_div": 30,
        "take_profit_pct": 40.0,
        "stop_loss_pct": 15.0,
        "hold_days": 252,
    },
}
